name: My first wprkflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "This is my first job running!"

        - name: List files
          run: ls

        - name: Read files
          run: cat README>md
